### ISSUE TITLE
关于秒杀的一些问题

### ISSUE THREAD

**Issue by wikimo** [newbee-ltd/newbee-mall-plus#17]
Hello，请教下秒杀方面的一些问题，谢谢！

1. 秒杀核心用到了存储过程，使用存储过程的优势是什么，为什么不去代码层处理而要交给存储过程；
2. 秒杀测试的服务器、DB配置环境如何；
3. 从实现看，将商品信息Cache到了Redis，库存扣减还是在于DB层，1秒 100000次请求，DB能抗住？

**Comment by wayn111** [comment]
1. 用存储过程是为了减少代码跟mysql通信次数，提升并发处理量
2. 秒杀测试服务器配置是虚拟机里2核2g，DB用的本地mysql
3. cache到redis是就是为了减少mysql访问量，扣减库存逻辑最后肯定还是走mysql，可以把令牌桶调小一点，1秒进来500个请求

**Comment by wikimo** [comment]
其实通过令牌桶限流后，虽然 1S 100000请求，实际有效成功秒杀1S 500个，剩下9500直接返回false了，没到DB，是这么理解吧？ @wayn111

**Comment by wayn111** [comment]
> 



> 其实通过令牌桶限流后，虽然 1S 100000请求，实际有效成功秒杀1S 500个，剩下9500直接返回false了，没到DB，是这么理解吧？ @wayn111

可以

**Comment by wikimo** [comment]
👌🏻，感谢解答 😄

**Comment by alittlenico** [comment]
关于秒杀的一些问题:
使用了redis来预热库存，并使用lua脚本扣减库存，但如果redis扣减成功，但后面逻辑出现问题并没有在db层面扣减成功，对于后面请求，由于redis库存全部扣减完了，直接抛错。这就导致db有库存但无法扣减，这个要怎么解决啊

**Comment by alittlenico** [comment]
> 关于秒杀的一些问题: 使用了redis来预热库存，并使用lua脚本扣减库存，但如果redis扣减成功，但后面逻辑出现问题并没有在db层面扣减成功，对于后面请求，由于redis库存全部扣减完了，直接抛错。这就导致db有库存但无法扣减，这个要怎么解决啊

这会造成少买问题
