### ISSUE TITLE
商品下单，支付金额未作校验

### ISSUE THREAD

**Issue by BairdWan** [newbee-ltd/newbee-mall-plus#5]
![image](https://user-images.githubusercontent.com/43845414/126106674-75b62956-9511-4cbc-b6dc-657d30aafaa5.png)
![image](https://user-images.githubusercontent.com/43845414/126106743-f02bde95-068c-42ea-80b1-8035018050fe.png)

**Comment by ZHENFENG13** [comment]
收到
