### ISSUE TITLE
沙箱支付验签问题

### ISSUE THREAD

**Issue by ArianChen777** [newbee-ltd/newbee-mall-plus#52]
作者大大，不知道为什么boolean signVerified = AlipaySignature.rsaCheckV1(params, alipayConfig.getAlipayPublicKey(), charset, signType);  一直返回false验签失败，不知道怎么解决啊。所有问题我都搜了，细节都检查了还是失败。

**Comment by ZHENFENG13** [comment]
检查公钥私钥，要不然重新申请公钥私钥试试
