### ISSUE TITLE
软件著作权 v.s. GPLv3

### ISSUE THREAD

**Issue by ysun** [newbee-ltd/newbee-mall-plus#7]
好奇的问下，在源代码保护方面，软件著作权和GPLv3是不是有点矛盾？
GPL基本上鼓励代码被商业使用，条件是保留原作者署名。 但软件著作权是不是有保护源代码不被使用？
我如何理解加了软件著作权的GPLv3 协议？
最近刚刚关注这个项目，然后知道慕课网的事情，当然我不关心慕课网。我只是好奇，这个商场还能否依照GPLv3的约定，商用？

**Comment by ZHENFENG13** [comment]
别想得太复杂。简单来说：你只要不恶心我，我也不会闲着没事去恶心你。
