### ISSUE TITLE
快速搭建文档？

### ISSUE THREAD

**Issue by ysun** [newbee-ltd/newbee-mall-plus#8]
如果商用没有问题了，有没有快速搭建的文档？简单看了下那个69元文档的目录，感觉说的不是一回事儿。
简单了解下，newbee大概由 后端newbee-mall-api, 和两个前端newbee-mall-vue3-app 和 vue3-admin组成。
能否有文档可以让不太熟悉的同学快速搭建起来，商用也好，学习也罢。
当然付费是能接受的。 这样是不是可以让项目推广的更快一点？毕竟除了code本身，还需要一些系统依赖，例如redis、myql 诸如此类的。

**Comment by ZHENFENG13** [comment]
那个掘金小册是2019年发售的，plus版本的代码是2021年年中才发上来，暂时还没时间整理文档。
